# config/packages/easy_admin.yaml
easy_admin:
    entities:
        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'email' }
                    - { property: 'plainPassword', type: 'password', label: 'Password' }
                    - { property: 'roles' }
